// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use a DIRECT connection (Supabase port 5432) when available,
    // falling back to DATABASE_URL. The app runtime uses the pooled
    // DATABASE_URL via the pg driver adapter (see src/lib/db.ts).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
